# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LeeNote
email: leetto@qq.com
description: |
  Welcome to LeeNote! 
  A hub for all things programming, algorithms, computer science, and math. Here, I document my learning journey, share insights, and break down complex concepts. Dive in, explore, and let’s geek out together!
baseurl: "/Leetto" # the subpath of your site, e.g. /blog
url: "http://Leetto-o.github.io" # the base hostname & protocol for your site
github_username: Leetto-o

# Build settings
markdown: kramdown
kramdown:
  math_engine: disabled     # 完全禁用 kramdown 的数学处理
theme: jekyll-theme-cayman
